package com.amaromerovic.flag.util

import com.amaromerovic.flag.model.Country

object Util {
    const val NAME_KEY = "name"
    const val CORRECT_KEY = "correct"

    fun getCountries(): ArrayList<Country> {
        val countries = ArrayList<Country>()

        var tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_afghanistan, "Afghanistan")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_albania, "Albania")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_algeria, "Algeria")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_andorra, "Andorra")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_angola, "Angola")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_antigua, "Antigua and Barbuda")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_argentina, "Argentina")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_armenia, "Armenia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_australia, "Australia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_austria, "Austria")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_azerbaijan, "Azerbaijan")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_bahamas, "Bahamas")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_bahrain, "Bahrain")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_bangladesh, "Bangladesh")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_barbados, "Barbados")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_belarus, "Belarus")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_belgium, "Belgium")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_belize, "Belize")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_benin, "Benin")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_bhutan, "Bhutan")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_bolivia, "Bolivia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_bosnia_herzegovina, "Bosnia and Herzegovina")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_botswana, "Botswana")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_brazil, "Brazil")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_brunei, "Brunei")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_bulgaria, "Bulgaria")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_burkina_faso, "Burkina Faso")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_burundi, "Burundi")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_cabo_verde, "Cabo Verde")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_cambodia, "Cambodia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_cameroon, "Cameroon")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_canada, "Canada")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_central_african_republic, "Central African Republic")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_chad, "Chad")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_chile, "Chile")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_china, "China")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_colombia, "Colombia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_comoros, "Comoros")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_congo_democratic_republic_of, "Democratic Republic of the Congo")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_congo, "Republic of the Congo")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_costa_rica, "Costa Rica")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_cote_d_ivoire, "Cote d'Ivoire")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_croatia, "Croatia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_cuba, "Cuba")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_cyprus, "Cyprus")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_czech_republic, "Czechia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_denmark, "Denmark")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_djibouti, "Djibouti")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_dominica, "Dominica")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_dominican_republic, "Dominican Republic")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_ecuador, "Ecuador")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_egypt, "Egypt")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_el_salvador, "El Salvador")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_equatorial_guinea, "Equatorial Guinea")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_eritrea, "Eritrea")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_estonia, "Estonia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_eswatini, "Eswatini")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_ethiopia, "Ethiopia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_fiji, "Fiji")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_finland, "Finland")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_france, "France")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_gabon, "Gabon")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_gambia, "Gambia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_georgia, "Georgia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_germany, "Germany")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_ghana, "Ghana")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_greece, "Greece")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_grenada, "Grenada")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_guatemala, "Guatemala")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_guinea, "Guinea")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_guinea_bissau, "Guinea-Bissau")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_guyana, "Guyana")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_haiti, "Haiti")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_honduras, "Honduras")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_hungary, "Hungary")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_iceland, "Iceland")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_india, "India")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_indonesia, "Indonesia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_iran, "Iran")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_iraq, "Iraq")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_ireland, "Ireland")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_israel, "Israel")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_italy, "Italy")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_jamaica, "Jamaica")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_japan, "Japan")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_jordan, "Jordan")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_kazakhstan, "Kazakhstan")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_kenya, "Kenya")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_kiribati, "Kiribati")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_kosovo, "Kosovo")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_kuwait, "Kuwait")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_kyrgyzstan, "Kyrgyzstan")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_laos, "Laos")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_latvia, "Latvia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_lebanon, "Lebanon")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_lesotho, "Lesotho")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_liberia, "Liberia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_libya, "Libya")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_liechtenstein, "Liechtenstein")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_lithuania, "Lithuania")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_luxembourg, "Luxembourg")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_madagascar, "Madagascar")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_malawi, "Malawi")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_malaysia, "Malaysia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_maldives, "Maldives")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_mali, "Mali")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_malta, "Malta")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_marshall_islands, "Marshall Islands")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_mauritania, "Mauritania")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_mauritius, "Mauritius")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_mexico, "Mexico")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_micronesia, "Micronesia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_moldova, "Moldova")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_monaco, "Monaco")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_mongolia, "Mongolia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_montenegro, "Montenegro")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_morocco, "Morocco")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_mozambique, "Mozambique")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_myanmar, "Myanmar")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_namibia, "Namibia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_nauru, "Nauru")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_nepal, "Nepal")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_netherlands, "Netherlands")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_new_zealand, "New Zealand")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_nicaragua, "Nicaragua")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_niger, "Niger")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_nigeria, "Nigeria")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_korea_north, "North Korea")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_north_macedonia, "North Macedonia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_norway, "Norway")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_oman, "Oman")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_pakistan, "Pakistan")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_palau, "Palau")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_palestine, "Palestine")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_panama, "Panama")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_papua_new_guinea, "Papua New Guinea")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_paraguay, "Paraguay")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_peru, "Peru")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_philippines, "Philippines")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_poland, "Poland")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_portugal, "Portugal")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_qatar, "Qatar")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_romania, "Romania")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_russia, "Russia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_rwanda, "Rwanda")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_st_kitts_nevis, "Saint Kitts and Nevis")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_st_lucia, "Saint Lucia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_st_vincent_the_grenadines, "Saint Vincent and the Grenadines")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_samoa, "Samoa")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_san_marino, "San Marino")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_sao_tome_and_principe, "Sao Tome and Principe")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_saudi_arabia, "Saudi Arabia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_senegal, "Senegal")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_serbia, "Serbia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_seychelles, "Seychelles")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_sierra_leone, "Sierra Leone")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_singapore, "Singapore")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_slovakia, "Slovakia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_slovenia, "Slovenia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_solomon_islands, "Solomon Islands")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_somalia, "Somalia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_south_africa, "South Africa")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_korea_south, "South Korea")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_south_sudan, "South Sudan")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_spain, "Spain")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_sri_lanka, "Sri Lanka")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_sudan, "Sudan")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_suriname, "Suriname")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_sweden, "Sweden")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_switzerland, "Switzerland")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_syria, "Syria")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_taiwan, "Taiwan")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_tajikistan, "Tajikistan")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_tanzania, "Tanzania")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_thailand, "Thailand")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_timor_leste, "Timor-Leste")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_togo, "Togo")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_tonga, "Tonga")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_trinidad_and_tobago, "Trinidad and Tobago")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_tunisia, "Tunisia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_turkey, "Turkey")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_turkmenistan, "Turkmenistan")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_tuvalu, "Tuvalu")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_uganda, "Uganda")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_ukraine, "Ukraine")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_united_arab_emirates, "United Arab Emirates")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_united_kingdom, "United Kingdom")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_united_states_of_america, "United States of America")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_uruguay, "Uruguay")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_uzbekistan, "Uzbekistan")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_vanuatu, "Vanuatu")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_vatican_city, "Vatican")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_venezuela, "Venezuela")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_vietnam, "Vietnam")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_yemen, "Yemen")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_zambia, "Zambia")
        countries.add(tempCountry)
        tempCountry = Country(com.amaromerovic.flag.R.drawable.flag_of_zimbabwe, "Zimbabwe")
        countries.add(tempCountry)

        return countries
    }

}